version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Route"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      compatible-updates:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/nodeJS_API/project1"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      compatible-updates:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/nodeJS_API/Project2"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      compatible-updates:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/nodeJS_API/Project3"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      compatible-updates:
        update-types:
          - "minor"
          - "patch"
